In [1]:
import pandas as pd

df = pd.read_csv('NIPS_1987-2015.csv')
del df['Unnamed: 0']
df

,1987_1,1987_2,1987_3,1987_4,1987_5,1987_6,1987_7,1987_8,1987_9,1987_10,...,2015_394,2015_395,2015_396,2015_397,2015_398,2015_399,2015_400,2015_401,2015_402,2015_403
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11458,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11459,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11460,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11461,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11462,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from scipy.cluster.hierarchy import linkage, dendrogram

Z = linkage(df, 'ward')

In [2]:
import matplotlib.pyplot as plt

%matplotlib inline

plt.figure()
dendrogram(Z)
plt.show()

NameError: name 'dendrogram' is not defined